### ISSUE TITLE
You are calling a deprecated version of the Ads API. Please update to the latest version: v2.8.

### ISSUE THREAD

**Issue by rahulmanayath** [edbizarro/laravel-facebook-ads#23]
$insights = $adsApi->insights();

 $adAccountInsights  = $insights->get('ad_account', 'act_88888', ['fields'=>[ 'ad_name']]);

**Comment by edbizarro** [comment]
hi @rahulmanayath 

I'm working on a [stable version](https://github.com/edbizarro/laravel-facebook-ads/tree/1.0) of this package with latest FB API

**Comment by rahulwayanad** [comment]
OK Thanks for your reply, I solved my problem.
