### ISSUE TITLE
"Interface 'tightenco\collect\Contracts\Support\Arrayable' not found"

### ISSUE THREAD

**Issue by Khalid12345678** [edbizarro/laravel-facebook-ads#33]
I am trying to use facebook api to get the details of my facebook ads. I have implemented your given package to laravel 5.6 with php 7.2.1. Now after implementing everything I am getting "Interface 'tightenco\collect\Contracts\Support\Arrayable' not found". Kindly look at the issue. Two screen shots are attached. 

<img width="960" alt="temp2" src="https://user-images.githubusercontent.com/35664838/42875168-a6de80da-8aa0-11e8-9a31-2de23f08838b.png">

<img width="960" alt="temp" src="https://user-images.githubusercontent.com/35664838/42874986-26bcd9a6-8aa0-11e8-94c0-bd4c5d0ad867.png">

**Comment by Braunson** [comment]
Also getting this..

**Comment by Braunson** [comment]
Pushed a fix for this in the attached PR.

**Comment by Khalid12345678** [comment]
Thank you so much Braunson...its working fine right now

**Comment by edbizarro** [comment]
Thk!

**Comment by Khalid12345678** [comment]
Thank you so much sir....It's very helpful for me
