### ISSUE TITLE
Non-static method Edbizarro\LaravelFacebookAds\AbstractFacebookAds::init() should not be called statically

### ISSUE THREAD

**Issue by DzinPerformmaOnline** [edbizarro/laravel-facebook-ads#35]
I'm getting this error when I add FacebookAds::init($accessToken); before using it. Also I needed to include use Edbizarro\LaravelFacebookAds\FacebookAds;

Error msg: Non-static method Edbizarro\LaravelFacebookAds\AbstractFacebookAds::init() should not be called statically

Any help, please??

**Comment by keedle** [comment]
Hello, catching the same error have you found a solution?
